# Generated by Django 4.0.5 on 2022-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField(default=0)),
                ('data_1', models.CharField(max_length=100)),
                ('data_2', models.CharField(max_length=100)),
            ],
        ),
    ]
